manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: elpekenin
      url-base: https://github.com/elpekenin
    - name: MickiusMousius
      url-base: https://github.com/MickiusMousius
  projects:
    - name: zmk
      import: app/west.yml
      remote: zmkfirmware
      revision: d32ffb0a335ece70a9ce3dc3ce014676534ee99b
    - name: zmk-userspace
      remote: elpekenin
      revision: main
    - name: zmk-ls0xxvcom-driver
      remote: MickiusMousius
      revision: main
  self:
    path: config
